# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\ncalculator\",\n\nRequestAdd\x12\x0e\n\x06inputA\x18\x01 \x01(\x01\x12\x0e\n\x06inputB\x18\x02 \x01(\x01\"\x1e\n\x0cRequestReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32G\n\nCalculator\x12\x39\n\x03\x41\x64\x64\x12\x16.calculator.RequestAdd\x1a\x18.calculator.RequestReply\"\x00\x42%\n\ncalculatorB\x0f\x43\x61lculatorprotoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_REQUESTADD = _descriptor.Descriptor(
  name='RequestAdd',
  full_name='calculator.RequestAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputA', full_name='calculator.RequestAdd.inputA', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputB', full_name='calculator.RequestAdd.inputB', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=76,
)


_REQUESTREPLY = _descriptor.Descriptor(
  name='RequestReply',
  full_name='calculator.RequestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.RequestReply.result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['RequestAdd'] = _REQUESTADD
DESCRIPTOR.message_types_by_name['RequestReply'] = _REQUESTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestAdd = _reflection.GeneratedProtocolMessageType('RequestAdd', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTADD,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.RequestAdd)
  ))
_sym_db.RegisterMessage(RequestAdd)

RequestReply = _reflection.GeneratedProtocolMessageType('RequestReply', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.RequestReply)
  ))
_sym_db.RegisterMessage(RequestReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\ncalculatorB\017CalculatorprotoP\001\242\002\003HLW'))

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='calculator.Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=110,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='calculator.Calculator.Add',
    index=0,
    containing_service=None,
    input_type=_REQUESTADD,
    output_type=_REQUESTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
